M48
; DRILL file {KiCad 7.0.8} date Tue Dec 10 03:26:14 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-10T03:26:14-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
%
G90
G05
T1
X129.545Y-66.38
X129.545Y-107.02
X144.785Y-66.38
X144.785Y-107.02
T0
M30
